server:
  port: 9002
  error:
    whitelabel:
      enabled: false
 
eureka:
  instance:
    hostname: ${discovery.host:localhost}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: itemreview.log
  level:
    com.springframework.cloud.netflix.eureka: debug
    com.netflix.eureka: debug
    com.netflix.discovery: debug

management:
  security:
    enabled: false
  port: 7880

---
spring:
  profiles: dockerC
  
discovery:
  host: eurekad